# IN-CSEが提供するMQTTブローカーの接続URL
cse_broker_urls: 
  - tcp://localhost:1883
  
# Subscribeするトピック名
topic_for_subscribe: oneM2M/req/ADN-AE/IN-CSE/json

# Publishするトピック名
topic_for_publish: oneM2M/req/IN-CSE/ADN-AE/json

spring.datasource.driver-class-name: net.sf.log4jdbc.DriverSpy
spring.datasource.url: jdbc:log4jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
logging.level.jdbc: OFF
logging.level.jdbc.sqltiming: DEBUG